### ISSUE TITLE
Thoughts on exposing a reason-promise interface?

### ISSUE THREAD

**Issue by erlandsona** [johnridesabike/bs-localforage#1]

**Comment by johnridesabike** [comment]
I like reason-promise quite a lot, but I want to stick to a plain Js.Promise for better interoperability. It only takes a couple of lines of code to convert a Js.Promse to a reason-promise ([in fact, that’s what I do in my own code](https://github.com/johnridesabike/coronate/blob/0d01a7d024721ac9d7ec85ae6d8f9fda56183dfe/src/Db.re#L74)), so I’d rather let users choose to do that themselves.
